import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Use local font files instead of Google Fonts
const geistSans = localFont({
  src: "../fonts/system-sans.woff2", // Using Inter as a fallback for Geist Sans
  variable: "--font-geist-sans",
  fallback: ["system-ui", "Arial", "sans-serif"],
  display: "swap",
  preload: false,
});

const geistMono = localFont({
  src: "../fonts/system-mono.woff2", // Using JetBrains Mono as a fallback for Geist Mono
  variable: "--font-geist-mono",
  fallback: ["Consolas", "monospace"],
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
